### ISSUE TITLE
Object(...) is not function error

### ISSUE THREAD

**Issue by Workaja** [sdey0081/ionic-messenger-starter#9]
TypeError: Object(...) is not a function
    at SwitchMapSubscriber.project (http://localhost:8100/build/vendor.js:71808:76)
    at SwitchMapSubscriber._next (http://localhost:8100/build/vendor.js:59236:27)
    at SwitchMapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:17882:18)
    at RefCountSubscriber.Subscriber._next (http://localhost:8100/build/vendor.js:17918:26)
    at RefCountSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:17882:18)
    at Subject.next (http://localhost:8100/build/vendor.js:20366:25)
    at ConnectableSubscriber.Subscriber._next (http://localhost:8100/build/vendor.js:17918:26)
    at ConnectableSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:17882:18)
    at Notification.observe (http://localhost:8100/build/vendor.js:48771:50)
    at AsyncAction.DelaySubscriber.dispatch (http://localhost:8100/build/vendor.js:74092:40)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.11.2
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by sdey0081** [comment]
Not sure how to reproduce it, but fortunately there will be a new version of `ionic-v4` within a few days. Thanks for your interesting.

**Comment by sdey0081** [comment]
Closing this issue with #12 .
